// <auto-generated />
using System;
using EfSamurai;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfSamurai.Migrations
{
    [DbContext(typeof(SamuraiContext))]
    partial class SamuraiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EfSamurai.Battle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("battleLogId");

                    b.Property<bool>("brutal");

                    b.Property<DateTime>("endDate");

                    b.Property<string>("name");

                    b.Property<DateTime>("startDate");

                    b.HasKey("id");

                    b.HasIndex("battleLogId");

                    b.ToTable("Battle");
                });

            modelBuilder.Entity("EfSamurai.BattleEvent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("battleLogId");

                    b.Property<string>("input");

                    b.Property<int>("order");

                    b.HasKey("id");

                    b.HasIndex("battleLogId");

                    b.ToTable("BattleEvent");
                });

            modelBuilder.Entity("EfSamurai.BattleLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("BattleLog");
                });

            modelBuilder.Entity("EfSamurai.Quote", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ownerid");

                    b.Property<int>("sort");

                    b.Property<string>("text");

                    b.HasKey("id");

                    b.HasIndex("ownerid");

                    b.ToTable("Quote");
                });

            modelBuilder.Entity("EfSamurai.Samurai", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("haircut");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Samurais");
                });

            modelBuilder.Entity("EfSamurai.SamuraisToBattle", b =>
                {
                    b.Property<int>("samuraiId");

                    b.Property<int>("battleId");

                    b.HasKey("samuraiId", "battleId");

                    b.HasIndex("battleId");

                    b.ToTable("SamuraisToBattle");
                });

            modelBuilder.Entity("EfSamurai.SecretIdentity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name");

                    b.Property<int>("samuraiId");

                    b.HasKey("id");

                    b.HasIndex("samuraiId")
                        .IsUnique();

                    b.ToTable("SecretIdentity");
                });

            modelBuilder.Entity("EfSamurai.Battle", b =>
                {
                    b.HasOne("EfSamurai.BattleLog", "log")
                        .WithMany()
                        .HasForeignKey("battleLogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EfSamurai.BattleEvent", b =>
                {
                    b.HasOne("EfSamurai.BattleLog", "battleLog")
                        .WithMany("battleEvents")
                        .HasForeignKey("battleLogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EfSamurai.Quote", b =>
                {
                    b.HasOne("EfSamurai.Samurai", "owner")
                        .WithMany("quoteList")
                        .HasForeignKey("ownerid");
                });

            modelBuilder.Entity("EfSamurai.SamuraisToBattle", b =>
                {
                    b.HasOne("EfSamurai.Battle", "battle")
                        .WithMany("stb")
                        .HasForeignKey("battleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EfSamurai.Samurai", "Samurai")
                        .WithMany("stb")
                        .HasForeignKey("samuraiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EfSamurai.SecretIdentity", b =>
                {
                    b.HasOne("EfSamurai.Samurai", "samurai")
                        .WithOne("identity")
                        .HasForeignKey("EfSamurai.SecretIdentity", "samuraiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
