// <auto-generated />
using System;
using CodeAlongDBquick;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeAlongDBquick.Migrations
{
    [DbContext(typeof(FruitContext))]
    partial class FruitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeAlongDBquick.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BTFBasketId");

                    b.Property<int?>("BTFFruitId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BTFBasketId", "BTFFruitId");

                    b.ToTable("Basket");
                });

            modelBuilder.Entity("CodeAlongDBquick.BasketToFruit", b =>
                {
                    b.Property<int>("BasketId");

                    b.Property<int>("FruitId");

                    b.HasKey("BasketId", "FruitId");

                    b.ToTable("BasketToFruit");
                });

            modelBuilder.Entity("CodeAlongDBquick.Fruit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BaskettyBasketId");

                    b.Property<int?>("BaskettyFruitId");

                    b.Property<int?>("BosseId");

                    b.Property<string>("Colour");

                    b.Property<string>("Name");

                    b.Property<decimal?>("Price");

                    b.HasKey("Id");

                    b.HasIndex("BosseId");

                    b.HasIndex("BaskettyBasketId", "BaskettyFruitId");

                    b.ToTable("Fruits");
                });

            modelBuilder.Entity("CodeAlongDBquick.FruitCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("FruitCategories");
                });

            modelBuilder.Entity("CodeAlongDBquick.Basket", b =>
                {
                    b.HasOne("CodeAlongDBquick.BasketToFruit", "BTF")
                        .WithMany("BasketList")
                        .HasForeignKey("BTFBasketId", "BTFFruitId");
                });

            modelBuilder.Entity("CodeAlongDBquick.Fruit", b =>
                {
                    b.HasOne("CodeAlongDBquick.FruitCategories", "Bosse")
                        .WithMany("FruitList")
                        .HasForeignKey("BosseId");

                    b.HasOne("CodeAlongDBquick.BasketToFruit", "Basketty")
                        .WithMany("FruitList")
                        .HasForeignKey("BaskettyBasketId", "BaskettyFruitId");
                });
#pragma warning restore 612, 618
        }
    }
}
